import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import "animate.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
